// <auto-generated />
using DailyDolce.Services.ProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyDolce.Services.ProductApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221017143336_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DailyDolce.Services.ProductAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Cupcake",
                            Description = "Come procuratori e che liberalita che lui sue spezial di impermutabile avvien sempre son tale sua dico prieghi manifesta noi",
                            ImageUrl = "https://gisramosrod.blob.core.windows.net/dailydolce/1.jpg",
                            Name = "Pumpkin Cupcake",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Cookie",
                            Description = "Ma giudice in nostri il carissime seguendo essaudisce per i i ignoranza e giudicio del di che viviamo forse nome",
                            ImageUrl = "https://gisramosrod.blob.core.windows.net/dailydolce/2.jpg",
                            Name = "Vanilla Cookies",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Cake",
                            Description = "Nome piú senza allo degli dalla prieghi i alcun alcun furon sí manifesta di primo cosí potra vostro quale cose",
                            ImageUrl = "https://gisramosrod.blob.core.windows.net/dailydolce/3.jpg",
                            Name = "Taiyaki",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Cake",
                            Description = "Vita mortali suo il da nella accio essaudisce del tanto nome coloro del per e le e quale manifestamente tutte",
                            ImageUrl = "https://gisramosrod.blob.core.windows.net/dailydolce/4.jpg",
                            Name = "Strawberry Cake",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
